version: "3"

services:
  # python:
  #   build: python310
  #   container_name: python
  #   volumes:
  #     - ../pythonProject/:/code
  #   tty: true
  #   ports:
  #     - 8037:8000
  #   depends_on:
  #     - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - ./dynamodb_data:/data
    ports:
      - 8000:8000

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
